name: Node.js CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 
      uses: actions/setup-node@v4
      with:
        node-version: "22"

    - name: Set up Newman
      run: |
        npm install -g newman@latest
        npm install -g newman-reporter-htmlextra@latest

    - name: Create directory for reports
      run: mkdir -p newman

    - name: List files
      run: ls -al

    - name: Run test with Newman
      run: |
        export NODE_NO_WARNINGS=1
        NODE_OPTIONS="--no-deprecation" newman run Test1.postman_collection.json --environment Test1.postman_environment.json -r htmlextra --reporter-htmlextra-export newman/reporte.html --verbose

    - name: Display error logs
      run: cat /home/runner/.npm/_logs/*-debug.log || true

    - name: Test Report Generation
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: Newman report
        path: newman/reporte.html
